name: My Workflow 
on: [push, workflow_dispatch]
jobs:
    lint:
      runs-on: ubuntu-latest
      steps: 
        - name: Get code
          uses: actions/checkout@v3
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Dependencies 
          run: npm ci
        - name: lint
          run: npm run lint
        - name: Run tests
          run: npm test

    deploy:
        needs: lint
        runs-on: ubuntu-latest
        steps: 
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Deploy
              run: echo "Deploying ..."

    run_scripts:
        needs: deploy
        runs-on: ubuntu-latest
        steps:
            - name: Get code